version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: arion_shots_db
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassRoot
      MYSQL_ROOT_PASSWORD: dbPassRoot
    ports:
      - '3306:3306'
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
